<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use App\Services\PermissionChecker;
use Database\Factories\UserFactory;
use Illuminate\Contracts\Translation\HasLocalePreference;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Hidden;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

#[Fillable(['company_id', 'name', 'email', 'preferred_locale', 'password'])]
#[Hidden(['password', 'remember_token'])]
class User extends Authenticatable implements HasLocalePreference
{
    /** @use HasFactory<UserFactory> */
    use HasFactory, Notifiable;

    /**
     * Get the company this user belongs to.
     *
     * @return BelongsTo<Company, $this>
     */
    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    /**
     * Get the roles assigned to this user.
     *
     * @return BelongsToMany<Role, $this>
     */
    public function roles(): BelongsToMany
    {
        return $this->belongsToMany(Role::class)
            ->withPivot('company_id')
            ->withTimestamps();
    }

    /**
     * Get the departments managed by this user.
     *
     * @return HasMany<Department, $this>
     */
    public function managedDepartments(): HasMany
    {
        return $this->hasMany(Department::class, 'manager_id');
    }

    /**
     * Get the employee profile linked to this user.
     *
     * @return HasOne<Employee, $this>
     */
    public function employeeProfile(): HasOne
    {
        return $this->hasOne(Employee::class);
    }

    /**
     * Get leave requests approved by this user.
     *
     * @return HasMany<LeaveRequest, $this>
     */
    public function approvedLeaveRequests(): HasMany
    {
        return $this->hasMany(LeaveRequest::class, 'approved_by');
    }

    /**
     * Get payroll periods closed by this user.
     *
     * @return HasMany<PayrollPeriod, $this>
     */
    public function closedPayrollPeriods(): HasMany
    {
        return $this->hasMany(PayrollPeriod::class, 'closed_by');
    }

    /**
     * Get payroll runs generated by this user.
     *
     * @return HasMany<PayrollRun, $this>
     */
    public function generatedPayrollRuns(): HasMany
    {
        return $this->hasMany(PayrollRun::class, 'generated_by');
    }

    /**
     * Get payroll runs approved by this user.
     *
     * @return HasMany<PayrollRun, $this>
     */
    public function approvedPayrollRuns(): HasMany
    {
        return $this->hasMany(PayrollRun::class, 'approved_by');
    }

    /**
     * Get CRM leads assigned to this user.
     *
     * @return HasMany<CrmLead, $this>
     */
    public function assignedCrmLeads(): HasMany
    {
        return $this->hasMany(CrmLead::class, 'assigned_user_id');
    }

    /** @return HasMany<CompanyApiToken, $this> */
    public function companyApiTokens(): HasMany
    {
        return $this->hasMany(CompanyApiToken::class);
    }

    /** @return HasMany<UserSession, $this> */
    public function trackedSessions(): HasMany
    {
        return $this->hasMany(UserSession::class);
    }

    public function hasPermission(string $permissionKey, ?int $companyId = null): bool
    {
        return app(PermissionChecker::class)->userHasPermission($this, $permissionKey, $companyId);
    }

    public function preferredLocale(): string
    {
        return $this->preferred_locale ?: ($this->company?->locale ?: 'ar');
    }

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }
}
